name: studentattendance
description: "A new Flutter project for Student Attendance System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  table_calendar: ^3.1.2
  percent_indicator: ^4.2.2
  http: ^1.1.0
  encrypted_shared_preferences: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
